FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ENV CHOKIDAR_USEPOLLING=true

#  Add this to expose the port
EXPOSE 5173

#  This tells Vite to listen on 0.0.0.0 instead of localhost
CMD ["npm", "run", "dev", "--", "--host"]
