name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build React Client
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/react-client:latest ./client

      - name: Build Node Server
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-server:latest ./server

      - name: Push React Client Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-client:latest

      - name: Push Node Server Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node-server:latest

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-client:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/node-server:latest
            docker stop client || true && docker rm client || true
            docker stop server || true && docker rm server || true
            docker run -d --name client -p 5173:5173 ${{ secrets.DOCKER_USERNAME }}/react-client:latest
            docker run -d --name server -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/node-server:latest
